INHERIT: plugins.yml

nav:
  - 首页:
      - README.md
      - awesome.md
      - github.md
      - tags.md
  - 新媒体:
      - media/README.md
  - 中医:
      - tcm/index.md
  - 开发:
      - dev/index.md
      - wechat:
          - wechat/index.md
          - wechat/oa.md
          - wechat/weapp-awesome.md
          - wechat/open/index.md
          - wechat/open/app/index.md
          - wechat/open/code/index.md
          - wechat/open/d3f/index.md
          - wechat/open/download/index.md
          - wechat/open/download/android.md
          - wechat/open/download/design.md
          - wechat/open/download/ios.md
          - wechat/open/download/wp8.md
      - aliyun:
          - aliyun/index.md
          - aliyun/video.md
      - 开发工具:
          - tools/index.md
          - Git:
              - tools/git/faq.md
          - eslint:
              - tools/eslint/index.md
          - vscode:
              - tools/vscode/index.md
              - tools/vscode/prettier.md
          - chrome:
              - tools/chrome/README.md
  - 语言:
      - langs/index.md
      - Node.js:
          - nodejs/index.md
          - nodejs/esm_chatgpt.md
          - nodejs/esm/index.md
          - nodejs/awesome.md
          - nodejs/express.md
          - nodejs/koa.md
          - nodejs/mongoose.md
          - nodejs/nodejs.md
          - nodejs/pm2.md
          - nodejs/modules/gm.md
          - nodejs/modules/node-rsa/jsbn.md
          - nodejs/modules/node-rsa/readme.md
          - nodejs/modules/qrcode/api.md
          - nodejs/modules/qrcode/readme.md
      - 前端:
          - React:
              - react/README.md
          - Angular:
              - angular/index.md
              - angular/angular.md
              - angular/awesome.md
              - angular/babel.md
              - angular/bit.md
              - angular/cli.md
              - angular/dart.md
              - angular/es5.md
              - angular/haxe.md
              - angular/ionic.md
              - angular/meteor.md
              - angular/migrate.md
              - angular/migrate6.md
              - angular/nativescript.md
              - angular/ngrx.md
              - angular/ngx-markdown.md
              - angular/react.md
              - angular/scala.md
              - angular/security.md
              - angular/sockets.md
              - angular/starter.md
              - angular/traceur.md
              - angular/typescript.md
              - angular/universal.md
              - angular/features/Test.md
          - Vue:
              - vue/README.md
          - jQuery:
              - jQuery/README.md
      - python:
          - python/README.md
          - pip:
              - python/pip/index.md
          - python/PyMongo.md
          - python/awesome.md
          - python/framework.md
          - Anaconda:
              - python/Anaconda/QuickStart.md
          - FullStack:
              - python/FullStack/mfap0.md
              - python/FullStack/mfap1.md
              - python/FullStack/mfap2.md
              - python/FullStack/mfap3.md
          - django:
              - python/django/index.md
              - python/django/awesome.md
          - flask:
              - python/flask/index.md
              - python/flask/awesome.md

      - Go:
          - langs/go/index.md
  - 智能:
      - ai/README.md
      - ai/awesome.md
      - NLP:
          - ai/deeplearning.md
          - ai/nlp.md
      - 博客:
          - ai/top.md
          - ai/2018.md
          - ai/2017-top-30.md
          - ai/2017.md
      - 机器人:
          - ai/bot/index.md
          - ai/bot/arduino.md
          - ai/bot/framework.md
          - ai/bot/ros.md
      - iot:
          - ai/iot/InternetOfThings.md
      - ai/jupyterlab.md
  - 区块链:
      - blockchain/index.md
      - blockchain/altcoins.md
      - blockchain/awesome.md
      - blockchain/term.md
      - blockchain/tree.md
      - blockchain/bitcoin/index.md
      - blockchain/ethereum/ProofOfStake.md
      - blockchain/ethereum/development.md
      - blockchain/ethereum/network-status.md
      - blockchain/ethereum/serpent.md
      - blockchain/ethereum/term.md
      - blockchain/ethereum/whitepaper.md
      - blockchain/ipfs/index.md
      - blockchain/twister/index.md
      - blockchain/twister/build-osx.md
      - blockchain/twister/build-unix.md
      - blockchain/twister/building-on-ubuntu-debian.md
      - blockchain/twister/compiling-for-windows.md
  - 农业:
      - agriculture/index.md
  - 教育:
      - education/README.md
      - education/kindergarten.md
      - education/primary-school.md
      - education/junior-middle-school.md
      - education/senior-middle-school.md
      - education/university.md
  - 运动:
      - fitness/index.md
      - fitness/walk.md
      - fitness/running.md
      - fitness/bicycle.md
      - fitness/card.md
  - 公寓:
      - apartment/index.md
      - apartment/1zu.md
      - apartment/boonself.md
      - apartment/danke.md
      - apartment/guanyu.md
      - apartment/inboyu.md
      - apartment/youranke.md
      - apartment/ziroom.md
  - 拼:
      - pin/index.md
      - pin/cohesion.md
      - pin/group.md
      - pin/ladder.md
      - pin/sku-spu.md
      - pin/fresh/education.md
      - pin/fresh/platform.md
      - pin/fresh/repository.md
  - 博客:
      - blog/README.md
