plugins:
  search:
    # Spaces, dashes, periods and forward-slash (so serving.knative.dev/blibble can be searched as blibble).
    separator: '[\/\s\-\.]+'
  # macros:
  #   module_name: hack/macros
  #   include_dir: source/snippets
  exclude:
    glob:
      # Exclude files that contain hugo specific shortcodes
      # (either the include shortcode or not-converted-yet tabs).
      - snippets/*
      - smoketest.md
  awesome-pages:
    filename: ".index"
    collapse_single_pages: true
    strict: false
  blogging:
    # locale: zh-CN
    # {{ blog_content }}
    dirs: # The directories to be included
      - blog
    features:
      tags: {}
    # {{ blog_content review }}
    categories:
      - name: review
        dirs:
          - review
  tags:
    tags_file: tags.md
